name: Batman
on:
  workflow_call:
    inputs:
      service-config:
        type: string
        required: false
jobs:
  build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy Service-1
        run: echo "Building and Deploying Service-1"