AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 with SG and VPC

Parameters:
  EnvName:
    Type: String
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  VpcId:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Existing Security Group ID
  InstanceType:
    Type: String
  ImageId:
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId # Replace with your region's AMI
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref SecurityGroupId
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install java-openjdk11 -y
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
          yum install jenkins -y
          systemctl enable jenkins
          systemctl start jenkins
          systemctl enable firewalld
          systemctl start firewalld
          firewall-cmd --permanent --zone=public --add-port=8080/tcp
          firewall-cmd --reload
