AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket

Parameters:
  EnvName:
    Type: String

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${EnvName}-bucket-test123"
