name: Test-Multifolder
on:
  push:
    branches: 
     - Test

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      folder1: ${{ steps.filter.outputs.folder1 }}
      folder2: ${{ steps.filter.outputs.folder2 }}
      folder3_test3: ${{ steps.filter.outputs.folder3_test3 }}
      folder3_test4: ${{ steps.filter.outputs.folder3_test4 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Detect changed folders
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            folder1:
              - 'Folder1/**'
            folder2:
              - 'Folder2/**'
            folder3_test3:
              - 'Folder3/Test3/**'
            folder3_test4:
              - 'Folder3/Test4/**'

  test_folder1:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.folder1 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder 1
        run: |
          echo "Testing Folder 1"

  test_folder2:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.folder2 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder 2
        run: |
          echo "Testing Folder 2"

  test_folder3_test3:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.folder3_test3 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder3/Test3
        run: |
          echo "Testing Folder3/Test3"

  test_folder3_test4:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: ${{ needs.detect_changes.outputs.folder3_test4 == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder3/Test4
        run: |
          echo "Testing Folder3/Test4"
