name: MultiFolder
on:
  push:
    branches: 
     - Multi_folder
     
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js for running JS files
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Use a specific Node.js version, adjust as needed
  test_folder1:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'folder1') }}  # Run if folder-1 is modified
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder 1
        run: |
          echo "Testing Folder 1"
          node folder-1/index.js   
  test_folder2:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'folder2') }}  # Run if folder-2 is modified
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder 2
        run: |
          echo "Testing Folder 2"
          node folder-2/index.js

  test_folder3:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'folder3') }}  # Run if folder-3 is modified
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests for Folder 3
        run: |
          echo "Testing Folder 3"
          node folder-3/index.js        