name: Service1-Caller

on:
  push:
    branches:
      - Test
    paths:
      - 'Folder1/**'

jobs:
  call_ci_service_1:
    name: ci_service_1
    uses: ./.github/workflows/ci_service_1.yml
    secrets: inherit
