name: Service2-Caller

on:
  push:
    branches:
      - Test
    paths:
      - 'Folder2/**'

jobs:
  call_ci_service_2:
    name: ci_service_2
    uses: ./.github/workflows/ci_service_2.yml
    secrets: inherit
